version: '2'

services:
  minion:
    image: psywolf/jmeter:latest
    mem_limit: 950m
    ports:
      - 1099:1099
      - 50000:50000
    volumes:
      - /logs:/logs
    environment:
      - CUSTOM_PLUGIN_URL=
